server {
    listen 443 ssl;
    server_name app1.lab;

    ssl_certificate /etc/nginx/ssl/lab.crt;
    ssl_certificate_key /etc/nginx/ssl/lab.key;

    location / {
        proxy_pass http://app1/;
    }
}

server {
    listen 443 ssl;
    server_name app2.lab;

    ssl_certificate /etc/nginx/ssl/lab.crt;
    ssl_certificate_key /etc/nginx/ssl/lab.key;

    location / {
        proxy_pass http://app2/;
    }
}
